Invalid HTTP_HOST header: 'api.jumiaonlineshopping.net'. You may need to add 'api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.jumiaonlineshopping.net'. You may need to add 'api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /favicon.ico
Not Found: /
Unauthorized: /api/accounts/
Internal Server Error: /static/rest_framework/css/bootstrap.min.css
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/csrf.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/bootstrap.min.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/prettify-min.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/default.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/load-ajax-form.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/css/prettify.css
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/css/default.css
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/css/bootstrap-tweaks.css
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/jquery-3.7.1.min.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/ajax-form.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/css/bootstrap.min.css
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/css/bootstrap-tweaks.css
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/css/prettify.css
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/csrf.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/bootstrap.min.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/default.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/prettify-min.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/load-ajax-form.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/css/default.css
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/ajax-form.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/jquery-3.7.1.min.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/css/bootstrap.min.css
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/jquery-3.7.1.min.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/ajax-form.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/css/prettify.css
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/csrf.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/prettify-min.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/default.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/bootstrap.min.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/css/bootstrap-tweaks.css
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/load-ajax-form.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/css/default.css
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/css/bootstrap.min.css
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/css/bootstrap-tweaks.css
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/csrf.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/bootstrap.min.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/css/prettify.css
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/default.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/prettify-min.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/load-ajax-form.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/jquery-3.7.1.min.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/css/default.css
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/rest_framework/js/ajax-form.js
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/views/static.py", line 34, in serve
    fullpath = Path(safe_join(document_root, path))
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "/opt/alt/python39/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /
Not Found: /
Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /
Not Found: /
Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Not Found: /
Not Found: /favicon.ico
Not Found: /
Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Not Found: /
Bad Request: /
Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Not Found: /
Bad Request: /
Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/jumioihg/virtualenv/api.jumiaonlineshopping.net/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.api.jumiaonlineshopping.net'. You may need to add 'www.api.jumiaonlineshopping.net' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /wp-admin/setup-config.php
Not Found: /wordpress/wp-admin/setup-config.php
Not Found: /
Not Found: /favicon.ico
Not Found: /
